[package]
name = "eddie-js"
version = "0.1.0"
authors = ["Ilia Schelokov <thaumant@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
eddie = "0.4"

[profile.release]
lto = "thin"
panic = "abort"
opt-level = 3
